sudo: required

services:
 - docker

language: node_js
node_js:
 - "10.12.0"
cache: npm

git:
  depth: 3

env:
 - NODE_ENV=development

install:
 - npm install

script:
 - eslint . --quiet

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull oxyl/sharders-to-handlers-device:latest
  - docker build -t oxyl/sharders-to-handlers-device:latest .
  - docker push oxyl/sharders-to-handlers-device:latest